version: '3.3'

services:
    mysql:
        image: mysql:8
        container_name: mysql_service
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: TianMiao
        volumes:
            - ./MySQL:/docker-entrypoint-initdb.d
    tomcat:
        build: ./
        container_name: tomcat_service
        ports:
            - 8080:8080
            - 9464:9464
        volumes:
            - ./opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
        environment:
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:55680
            - OTEL_RESOURCE_ATTRIBUTES=service.name=demo
            - JAVA_OPTS=-javaagent:/opentelemetry-javaagent.jar -Dlogging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG '-Dlogging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg traceID=%X{trace_id} %n'
        depends_on:
            - mysql
        logging:
            driver: loki
            options:
                loki-url: 'http://localhost:3100/api/prom/push'
    tempo:
        image: grafana/tempo:1.0.0
        command: ["--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false", "--config.file=/etc/tempo.yaml"]
        volumes:
            - ./config/tempo/tempo.yaml:/etc/tempo.yaml
            - ./tempo-data:/tmp/tempo
        ports:
            - "14268:14268"  # jaeger ingest
            - "3200:3200"   # tempo
            - "55680:55680"  # otlp grpc
            - "55681:55681"  # otlp http
            - "9411:9411"   # zipkin
    loki:
        image: grafana/loki:2.2.0
        command: -config.file=/etc/loki/local-config.yaml
        ports:
            - "3100:3100"
        logging:
            driver: loki
            options:
                loki-url: 'http://localhost:3100/api/prom/push'
    grafana:
        image: grafana/grafana:7.5.11
        volumes:
            - ./config/grafana:/etc/grafana/provisioning/datasources
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        ports:
            - "3000:3000"
        logging:
            driver: loki
            options:
                loki-url: 'http://localhost:3100/api/prom/push'
